server:
  port: 8080

spring:
  # 타임리프 설정
  thymeleaf:
    cache: false
    check-template: true
    prefix: classpath:templates/
    suffix: .html

  # devtools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # db 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: shop_db
    password: qwer1234

  # 시큐리티 설정
  security:
    user:
      name: admin       # 기본 로그인 아이디 (기본 보안 설정 사용 시)
      password: admin   # 기본 비밀번호
    oauth2:
      client:
        provider:
          # 네이버
          naver: 
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          naver:
            client-id: I9g8434xAG02CHu8Nf9g
            client-secret: nZ3Epi1bUj
            scope:
              - name
              - email
              - gender
              - birthday
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver


  mvc:                  # swagger 설정
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.shop.shop.user  # VO, DTO 위치
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    enabled: true  # API 문서(`/v3/api-docs`) 활성화 여부 (기본값: true)
    path: /v3/api-docs  # API 문서의 엔드포인트 변경 (기본값: /v3/api-docs)
    groups.enabled: true  # 여러 개의 API 그룹을 지원할지 여부

  swagger-ui:
    enabled: true  # Swagger UI 활성화 여부 (기본값: true)
    path: /swagger-ui.html  # Swagger UI 접속 경로 변경 (기본값: /swagger-ui.html)
    operationsSorter: method  # API 정렬 기준 (alpha: 알파벳순, method: HTTP 메서드 순)
    tagsSorter: alpha  # 태그 정렬 방식 (alpha: 알파벳순 정렬)
    display-request-duration: true  # 요청 실행 시간 표시 여부
    doc-expansion: none  # Swagger UI에서 API 설명의 기본 펼침 상태 (none: 닫힘, list: 펼침, full: 전체 펼침)
    persistAuthorization: true  # 페이지 새로고침 후에도 Authorization 헤더 유지 여부
    defaultModelsExpandDepth: -1  # 모델 스키마의 기본 펼침 깊이 (-1이면 모델 펼쳐지지 않음)

  paths-to-match:  # OpenAPI 문서에서 포함할 엔드포인트 패턴
    - /api/**  # /api로 시작하는 모든 경로 포함
    - /admin/**  # /admin으로 시작하는 모든 경로 포함
  cache:
    disabled: true  # OpenAPI 문서의 캐싱 비활성화 (기본값: false)
  show-actuator: false  # Spring Actuator 엔드포인트를 Swagger UI에 표시할지 여부 (기본값: false)
  servers:
    - url: http://localhost:8080  # 기본 서버 URL 설정
      description: "Local 개발 환경"
    - url: https://api.example.com  # 운영 서버 URL 설정
      description: "Production 서버"

# application.yml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true